#---------------------------------------

# Eco Bot By V8

#---------------------------------------

discord: 
  botToken: ""
  mongoDBLink: ""

discordCustomization: 
  embedColor: "RED"
  embedFooterText: ""